services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techlibrary_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=techlibrarydb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: techlibrary_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techlibrarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: